//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudgetClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeBudgetClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request result..
        /// </summary>
        internal static string Error_InvalidRequestResult {
            get {
                return ResourceManager.GetString("Error_InvalidRequestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id. Relogin to fix an error..
        /// </summary>
        internal static string Error_InvalidUserId {
            get {
                return ResourceManager.GetString("Error_InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token getting error: {0}..
        /// </summary>
        internal static string Error_TokenGetting {
            get {
                return ResourceManager.GetString("Error_TokenGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token saving error: {0}..
        /// </summary>
        internal static string Error_TokenSaving {
            get {
                return ResourceManager.GetString("Error_TokenSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data removing error: {0}..
        /// </summary>
        internal static string Error_UserDataRemoving {
            get {
                return ResourceManager.GetString("Error_UserDataRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id getting error: {0}..
        /// </summary>
        internal static string Error_UserIdGetting {
            get {
                return ResourceManager.GetString("Error_UserIdGetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content to sync found..
        /// </summary>
        internal static string Info_NoContentToSync {
            get {
                return ResourceManager.GetString("Info_NoContentToSync", resourceCulture);
            }
        }
    }
}
